name: RedstoneCommand
api-version: 1.13
main: de.homerbond005.redstonecommand.RedstoneCommand
version: ${project.version}
author: Tim van Gompel, PlayParadise, HomerBond005, SBDeveloper
description: Toggle redstone via a command.
softdepend: [Multiverse-Core, MyWorlds, MultiWorld]
commands:
    rsc:
        description: Toggles redstone power and provides other functions.
        usage: Type /<command> for help.